In [2]:
from autoMMM.autoholidays import HolidayExtractor

In [3]:
# Usage:
country = 'US'
start_date = '2023-01-01'
end_date = '2023-12-31'
week_start = 'Monday'

holiday_extractor = HolidayExtractor(country, start_date, end_date)

# Get holidays for a specific region
region = 'CA'
regional_holidays = holiday_extractor.get_holidays_by_region(region)

# Generate timeseries with custom holiday list
custom_holiday_list = ['New Year\'s Day', 'Christmas Day', 'Easter Sunday', 'Eid al-Fitr', 'Diwali']
weekly_timeseries_df = holiday_extractor.generate_timeseries(week_start=week_start, custom_holiday_list=custom_holiday_list)

weekly_timeseries_df

   Week Commencing  Is Holiday  Custom Holiday  Weeks Since Last Holiday
0       2022-12-26           1               1                         0
1       2023-01-02           1               0                         1
2       2023-01-09           0               0                         0
3       2023-01-16           1               0                         2
4       2023-01-23           0               0                         0
5       2023-01-30           0               0                         0
6       2023-02-06           0               0                         0
7       2023-02-13           0               0                         0
8       2023-02-20           1               0                         5
9       2023-02-27           0               0                         0
10      2023-03-06           0               0                         0
11      2023-03-13           0               0                         0
12      2023-03-20           0               0                         0
13      2023-03-27           0               0                         0
14      2023-04-03           0               0                         0
15      2023-04-10           0               0                         0
16      2023-04-17           0               0                         0
17      2023-04-24           0               0                         0
18      2023-05-01           0               0                         0
19      2023-05-08           0               0                         0
20      2023-05-15           0               0                         0
21      2023-05-22           0               0                         0
22      2023-05-29           1               0                        14
23      2023-06-05           0               0                         0
24      2023-06-12           0               0                         0
25      2023-06-19           1               0                         3
26      2023-06-26           0               0                         0
27      2023-07-03           1               0                         2
28      2023-07-10           0               0                         0
29      2023-07-17           0               0                         0
30      2023-07-24           0               0                         0
31      2023-07-31           0               0                         0
32      2023-08-07           0               0                         0
33      2023-08-14           0               0                         0
34      2023-08-21           0               0                         0
35      2023-08-28           0               0                         0
36      2023-09-04           1               0                         9
37      2023-09-11           0               0                         0
38      2023-09-18           0               0                         0
39      2023-09-25           0               0                         0
40      2023-10-02           0               0                         0
41      2023-10-09           1               0                         5
42      2023-10-16           0               0                         0
43      2023-10-23           0               0                         0
44      2023-10-30           0               0                         0
45      2023-11-06           2               0                         4
46      2023-11-13           0               0                         0
47      2023-11-20           1               0                         2
48      2023-11-27           0               0                         0
49      2023-12-04           0               0                         0
50      2023-12-11           0               0                         0
51      2023-12-18           0               0                         0
52      2023-12-25           1               1                         5